## Filtering ineligible functions
# spring.cloud.function.ineligible-definitions=foo,bar
#
#spring.cloud.function.stream.processor.name:uppercase
#spring.cloud.function.scan.packages:com.example.functions
spring:
  cloud:
    function:
      definition: uppercase