## Filtering ineligible functions
# spring.cloud.function.ineligible-definitions=foo,bar
#
#spring.cloud.function.stream.processor.name:uppercase
#spring.cloud.function.scan.packages:com.example.functions
#spring:
#  cloud:
#    function:
#      definition: uppercaseFlux;reverseFlux;uppercase;reverse;uppercaseFlux|reverseFlux
spring:
  cloud:
    function:
      location: /home/farhad/apps/my-examples/spring-cloud-function/deploying-packaged-functoion-example/normal-uppercase-function-example/target/normal-uppercase-function-example-0.0.1-SNAPSHOT.jar
      function-class: com.farhad.example.function.uppercase.UppercaseFunction;com.farhad.example.function.uppercase.ReverseFunction